# -*- coding: utf-8 -*-
"""pca-dimensionality-reduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idBI9dt6pUowpf56jk9_LW5N5Mc7gL-_

# Principal Component Analysis (PCA) for Dimensionality Reduction

## Project Overview

This project demonstrates the use of **Principal Component Analysis (PCA)**, a widely used dimensionality reduction technique in unsupervised machine learning.

The objective is to reduce a high-dimensional dataset into two principal components while preserving as much of the original data variance as possible.

The transformed dataset is then visualised to understand how PCA projects high-dimensional data into a lower-dimensional space.

# 📚 Import Required Libraries

Import the Python libraries required for synthetic data generation, preprocessing, dimensionality reduction, and visualisation.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

"""# 📊 Generate Synthetic Dataset

Generate a synthetic dataset using Scikit-learn's `make_blobs()` function.

The dataset contains multiple numerical features and three distinct clusters, making it suitable for demonstrating dimensionality reduction using PCA.
"""

X, y = make_blobs(n_samples=500, n_features=5, centers=3, cluster_std=1.5, random_state=42)

"""# 🔍 Explore the Dataset

Display the generated dataset to understand its structure before applying preprocessing and dimensionality reduction.
"""

X

"""# 🧹 Feature Scaling

Standardise the numerical features using **StandardScaler**.

Feature scaling is an important preprocessing step before applying PCA because the algorithm is sensitive to differences in feature scales.
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# ✅ Standardised Dataset

Display the scaled dataset after applying feature standardisation.
"""

X_scaled

"""# 📉 Apply Principal Component Analysis (PCA)

Reduce the original feature space to **two principal components** using Principal Component Analysis.

These principal components capture the maximum possible variance while reducing the dimensionality of the dataset.
"""

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

"""# 📊 PCA Output

Display the transformed dataset after dimensionality reduction.

Each observation is now represented using two principal components instead of the original feature set.
"""

X_pca

"""# 📋 Create PCA DataFrame

Convert the transformed principal components into a Pandas DataFrame and append the original cluster labels for visualisation.
"""

df_pca = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
df_pca['label'] = y

"""# 📈 Visualise Principal Components

Create a scatter plot of the first two principal components.

The visualisation illustrates how PCA separates the observations in the reduced two-dimensional feature space.
"""

sns.scatterplot(data=df_pca, x='PC1', y='PC2', hue='label', palette='Set2')

"""# Conclusion

This project demonstrated how **Principal Component Analysis (PCA)** can reduce the dimensionality of a dataset while preserving most of its important information.

The workflow included generating a synthetic dataset, standardising the features, applying PCA to obtain two principal components, and visualising the transformed data.

This project provides practical experience in dimensionality reduction, feature preprocessing, unsupervised machine learning, and data visualisation using Python and Scikit-learn.
"""

